### ISSUE TITLE
Better Routing Algorithm

### ISSUE THREAD

**Issue by JosuaKrause** [JosuaKrause/BusVis#15]
The routing algorithm is broken and should be fixed. From #14:

Because only one "shortest" path to each station is considered, quicker routes that avoid line changes aren't always taken:

```
   , 00:00 ---1--- 00:01.
  /                      \
(A) 00:01 ---2---> 00:02 (B) 00:02 ---2---> 00:03 (C)
                           \                      /
                            ` 00:03 ---3--- 00:04´
```

The optimal route (when change time is greater than zero) would be _Line 2_, but because _(B)_ is reached quicker by _Line 1_, it is taken instead.

**Comment by LeoWoerteler** [comment]
I wrote a new routing algorithm that also considers non-optimal intermediate states when the end result is optimal due to avoided changing of routes. It's slower than the old algorithm (more intermediate states, obviously) but doesn't look too bad. More tests have to be written.

I also wrote a facility for interruptible concurrent routing for use in the GUI.

Code review would be great: https://github.com/LeoWoerteler/BusVis/commit/c8155cf5

**Comment by LeoWoerteler** [comment]
@MarcSpicker, @feeras: your input would be great, too.

**Comment by JosuaKrause** [comment]
I'll have a look at it this evening
As far as I could see: you moved the whole route finder in its own class? That
keeps BusStation clean.
In BusStationTests I expanded the continuous test case (branch: master) which is not yet reflected in the routing
test class.

Am 16.06.2012 um 19:03 schrieb Leo Wörteler:

**Comment by JosuaKrause** [comment]
looks like its fixed now
