### ISSUE TITLE
Better GUI components

### ISSUE THREAD

**Issue by MarcSpicker** [JosuaKrause/BusVis#38]
The GUI elements that are used for choosing the time are not very intuitive.  Changing them to more "common" elements.

**Comment by JosuaKrause** [comment]
Why is change time, max wait, and max walk implemented as spinner? A slider would be more intuitive in those cases, since we can directly choose a time. (btw max walk needs maximal to be 2h)

**Comment by MarcSpicker** [comment]
Values can also be directly written into the spinners. If the others also think that a slider is more appropriate for choosing time, I will change it back.

**Comment by JosuaKrause** [comment]
The main problem of the sliders were that they change their sizes? (Can be fixed with setMaximumSize(getPreferredSize()) )
When you type in values you have no idea what meaningful values are (actually you can type in values that are not reachable, e.g. 25 as hours which will result in an exception).
A slider gives the user a boundary, e.g. in the max walk time, when the slider is set to far left, we do not walk, when the slider is on the far right, we will walk every distance. It gives a sense of relation (in terms of whether the value we have is big or small). Spinners are useful for absolute times though, since we there is no biggest or smallest time (we also can jump straight from 23:59 to 0:00)
What are the opinions of the others? (@feeras, @LeoWoerteler)
